### ISSUE TITLE
Equipment Company Contract

### ISSUE THREAD

**Issue by CarolynT2017** [azoff/wedding#29] opened 2017-02-08 06:10 UTC
tweaking with equipment you select can be done right up until the wedding, but you need a contract with the equipment rental company at least a month in advance.

Use Google to find a good equipment vendor.

Make a list of waht your various vendors supply, so you know what you need from the rentals.

**Comment by azoff** [comment] 2017-02-09 04:52
Duplicate of #30

**Closed by azoff** 2017-02-09 04:52 UTC
